aevatarAI/aevatar-station

- src/Aevatar.CQRS/Dto/SaveStateCommand.cs
- src/Aevatar.CQRS/ElasticIndexingService.cs
- src/Aevatar.CQRS/Handler/SaveStateCommandHandler.cs
- src/Aevatar.CQRS/IIndexingService.cs
- test/Aevatar.Cqrs.Tests/Cqrs/CqrsProviderTest.cs
- test/Aevatar.Cqrs.Tests/Cqrs/CqrsServiceTest.cs
- test/Aevatar.Cqrs.Tests/Cqrs/Dto/CqrsTestAgentState.cs
1. Create es state index 
2. Save state to es
3. UT
> atomic agent state save to es

- Directory.Packages.props
> support orlean 9.0.1

- src/Aevatar.Application.Contracts/CQRS/AgentEventLogsDto.cs
- src/Aevatar.Application.Contracts/CQRS/AgentStateDto.cs
- src/Aevatar.Application/AevatarApplicationAutoMapperProfile.cs
- src/Aevatar.Application/Service/AgentService.cs
- src/Aevatar.Application/Service/CqrsService.cs
- src/Aevatar.Application/Service/ICqrsService.cs
- src/Aevatar.CQRS/Dto/AgentGEventIndex.cs
- src/Aevatar.CQRS/ElasticIndexingService.cs
- src/Aevatar.CQRS/Provider/CQRSProvider.cs
- src/Aevatar.CQRS/Provider/ICQRSProvider.cs
- src/Aevatar.Domain.Shared/Cqrs/CQRSConstant.cs
- src/Aevatar.Domain/Agent/AgentDto.cs
- src/Aevatar.HttpApi/Controllers/QueryController.cs
end points for querying agent state and event logs. #54
> add CQRS query endpoint

- src/Aevatar.Application/Service/AgentService.cs
- src/Aevatar.Domain/Agent/CreateAgentInputDto.cs
> add agent customer id

- Directory.Packages.props
- src/Aevatar.Application.Contracts/Aevatar.Application.Contracts.csproj
- src/Aevatar.Application.Contracts/Exceptions/ParameterValidateException.cs
- src/Aevatar.Application.Contracts/Schema/ISchemaProvider.cs
- src/Aevatar.Application.Grains/Aevatar.Application.Grains.csproj
- src/Aevatar.Application/AevatarApplicationModule.cs
- src/Aevatar.Application/Schema/IgnoreSpecificBaseProcessor.cs
- src/Aevatar.Application/Schema/SchemaProvider.cs
- src/Aevatar.Application/Service/AgentService.cs
- src/Aevatar.Domain/Aevatar.Domain.csproj
- src/Aevatar.Domain/Agent/AgentDto.cs
- src/Aevatar.Domain/Agent/AgentTypeDto.cs
(1)response client json schema
(2)service json schema validate
> Json schema

- src/Aevatar.AuthServer/AevatarAuthServerModule.cs
- src/Aevatar.HttpApi.Host/AevatarHttpApiHostModule.cs
- src/Aevatar.WebHook.Host/AevatarWebHookHostModule.cs
> Feature: health check

- Directory.Packages.props
- src/Aevatar.Silo/Aevatar.Silo.csproj
- src/Aevatar.Silo/Extensions/OrleansHostExtension.cs
> llm add deepseek

- src/Aevatar.Developer.Host/Extensions/OrleansHostExtensions.cs
- src/Aevatar.HttpApi.Host/Extensions/OrleansClientExtension.cs
- src/Aevatar.Silo/Extensions/OrleansHostExtension.cs
- src/Aevatar.WebHook.Host/Extensions/OrleansHostExtensions.cs
- src/Aevatar.Worker/Extensions/OrleansClientExtension.cs
- Fixed mongodb collection issue
> Fix/update orleans config for MongoDB

- src/Aevatar.Application.Grains/Agents/Creator/CreatorGAgent.cs
- src/Aevatar.Application/AevatarApplicationAutoMapperProfile.cs
- src/Aevatar.Application/Service/AgentService.cs
- src/Aevatar.Application/Service/SubscriptionAppService.cs
- src/Aevatar.Domain.Shared/Agents/Creator/CreatorGAgentState.cs
- src/Aevatar.Domain/Subscription/EventTypeDto.cs
1.Support publishing a GEvent with new parameters in the original group
2.Support publishing a new type of GEvent in the original group
> Optimize GEvent publishing

- src/Aevatar.Silo/Extensions/OrleansHostExtension.cs
> feat:support muti topic

- test/Aevatar.Domain.Tests/AevatarDomainTestModule.cs
- test/Aevatar.MongoDB.Tests/MongoDb/AevatarMongoDbTestModule.cs
- test/Aevatar.TestBase/AevatarTestBaseModule.cs
- Fixed an issue with running unit tests using MongoDB.
- Fixed an issue with unit test startup initialization seed data.
> Fix: unit test cannot runs

- src/Aevatar.AuthServer/Dtos/ManagerCacheDto.cs
- src/Aevatar.AuthServer/ManagerCheckHelper.cs
- src/Aevatar.AuthServer/Options/SignatureGrantOptions.cs
- src/Aevatar.AuthServer/Provider/WalletLoginProvider.cs
- src/Aevatar.AuthServer/appsettings.json
1、check aa server api when gql and chain do not have manager address
> auth check portkey cache

- src/Aevatar.Aspire/Aevatar.Aspire.csproj
- src/Aevatar.Aspire/Program.cs
- src/Aevatar.Aspire/README.md
- src/Aevatar.Aspire/appsettings.json
1、Setup API key upon starting aspire and all its services
2、Allow developer to not spin up new databases through command line input when starting the program
3、Setup Developer's Silo
> aspire improvements

- src/Aevatar.AuthServer/AppleGrantHandler.cs
1. Apple login supports multiple redirect URLs
> Multi Redirect Uri

- src/Aevatar.Application.Contracts/ApiKeys/ProjectAppIdListResponseDto.cs
- src/Aevatar.Application.Contracts/Notification/INotificationService.cs
- src/Aevatar.Application.Contracts/Notification/NotificationDto.cs
- src/Aevatar.Application.Contracts/Notification/ReadNotificationDto.cs
- src/Aevatar.Application.Contracts/SignalR/SignalRMessage/UnreadNotificationResponse.cs
- src/Aevatar.Application/AevatarApplicationAutoMapperProfile.cs
- src/Aevatar.Application/Notification/NotificationService.cs
- src/Aevatar.Application/Notification/NotificationWrapper.cs
- src/Aevatar.Application/Service/ProjectAppIdService.cs
- src/Aevatar.Domain.Shared/Notification/NotificationStatusEnum.cs
- src/Aevatar.Domain/Notification/NotificationInfo.cs
- src/Aevatar.HttpApi/Controllers/NotificationController.cs
- Dto uses the utc timestamp.
- Fixed message read status.
- Fixed Api Key creator display.
> Fix: Developer platform v0.1

- .gitignore
- samples/VerifyStreamApp/Program.cs
- samples/VerifyStreamApp/VerifyStreamApp.csproj
1. add a test app to verify event publish/subscribe using Aevatar.Aspire/Aevatar.Silo projects 
2. add ignored files
> Add A Simple Test App to Validate Event Publish/Subscribe

- src/Aevatar.CQRS/AevatarStateProjector.cs
- src/Aevatar.CQRS/Options/ProjectorBatchOptions.cs
Add periodic timer to resolve batch flush latency issues in CQRS.
> Fix: Batch flush periodic timer

- src/Aevatar.Application/Service/AgentService.cs
Add support to allow register agent in batches to replace the existing logic which register agent one by one
Before:
After:
> [Performance] enable agent registration in batch

- samples/VerifyDbIssue545/VerifyDbIssue545.csproj
- samples/VerifyJsonDesIssue/VerifyJsonDesIssue.csproj
- samples/VerifySiloPlacement/VerifySiloPlacement.csproj
- samples/VerifyStreamApp/Program.cs
- samples/VerifyStreamApp/VerifyStreamApp.csproj
- Fix sample test compile error due to local source code 
- Remove local source code reference from sample projects
> [Fix] Sample test compile error

- samples/E2E.Grains/E2E.Grains.csproj
- samples/E2E.Grains/TestDbGAgent.cs
- samples/VerifyDbIssue545/Program.cs
- samples/VerifyDbIssue545/Program.cs.single
- samples/VerifyDbIssue545/VerifyDbIssue545.csproj
- samples/VerifyJsonDesIssue/Program.cs
- samples/VerifyJsonDesIssue/VerifyJsonDesIssue.csproj
- samples/VerifySiloPlacement/Program.cs
- samples/VerifySiloPlacement/VerifySiloPlacement.csproj
- samples/VerifyStreamApp/Program.cs
- samples/VerifyStreamApp/VerifyStreamApp.csproj
Move test agent to E2E.Grains projects to avoid activation in testing environment
> Move test agent to E2E.Grains projects

- src/Aevatar.CQRS/ElasticIndexingService.cs
Version check when insertion is causing issues as the upstream does not always sent all versions, instead some versions are missing e.g. version 1, which causes the insertion failure. Handle insertion in script is more elegant and less error-prone
Unit test
E2E tests
Insert Version 2 without version 1
Insert Version 4 without version 3
Omit update when version is equal to 4 (manually modify version from higher to 4 during debug)
> Remove version check and add ctx.op script to verify insert

- NuGet.Config
- Improve the nuget restore efficiency 
- remove BlazoriseMyGet as no packages are stored there for dev branch
> [Enhancement] Improve the nuget configuration

- Directory.Packages.props
- scripts/regression_test.py
- src/Aevatar.Application.Grains/Aevatar.Application.Grains.csproj
- src/Aevatar.Application.Grains/Agents/Creator/CreatorGAgent.cs
- src/Aevatar.Application/Schema/SchemaProvider.cs
- src/Aevatar.Application/Service/AgentService.cs
- src/Aevatar.Domain.Shared/Agents/Creator/CreatorGAgentState.cs
- src/Aevatar.Domain.Shared/Agents/Creator/GEvents/CreateAgentGEvent.cs
- src/Aevatar.Domain/Agent/AgentDto.cs
- src/Aevatar.Domain/Agent/AgentInstanceDto.cs
> merge dashboard

- Directory.Packages.props
- src/Aevatar.Application.Contracts/Profiles/IProfileService.cs
- src/Aevatar.Application.Contracts/Profiles/UserInfoDto.cs
- src/Aevatar.Application/AevatarApplicationModule.cs
- src/Aevatar.Application/Service/GodGPTService.cs
- src/Aevatar.Application/Service/ProfileService.cs
- src/Aevatar.GodGPT/Dtos/GetInvitationInfoResponse.cs
- src/Aevatar.GodGPT/Dtos/RedeemInviteCodeRequest.cs
- src/Aevatar.HttpApi/Controllers/GodGPTController.cs
- src/Aevatar.HttpApi/Controllers/GodGPTInvitationController.cs
- src/Aevatar.HttpApi/Controllers/ProfileController.cs
- src/Aevatar.Silo/Extensions/OrleansHostExtension.cs
- src/Aevatar.Silo/HybridGrainStateSerializer.cs
1. Invite friends to earn points.
2. Orleans binary serialization.
3. Add user information display to profile
> [GodGPT][1.19.0] User Invitations

- Directory.Packages.props
- src/Aevatar.Application.Contracts/Quantum/QuantumShareResponseDto.cs
- src/Aevatar.Application/Service/GodGPTService.cs
- src/Aevatar.GodGPT/Dtos/SessionType.cs
- src/Aevatar.GodGPT/Dtos/SessionTypeExtensions.cs
- src/Aevatar.HttpApi/Controllers/GodGPTController.cs
> Add getShareKeywork method

- framework/aevatar-framework.sln
- framework/samples/BroadCastGAgentDemo/Program.cs
- framework/samples/MessagingGAgent/MessagingGAgent.Grains/Agents/Messaging/DemoGAgent.cs
- framework/src/Aevatar.Core.Abstractions/Application/BroadcastGState.cs
- framework/src/Aevatar.Core/BroadcastGAgentBase.cs
- station/samples/AgentWarmupE2E/Fixtures/AgentWarmupTestFixture.cs
- station/samples/E2E.Grains/BroadcastAgents.cs
- station/samples/E2E.Grains/TestDbGAgent.cs
- station/samples/VerifyDbIssue545/Program.cs
- station/samples/VerifySiloPlacement/Program.cs
- station/samples/VerifyStreamApp/Program.cs
Rename "BroadCastGAgentBase" to "BroadcastGAgentBase" and its related state / events with lowercase
> Rename broadcast base agent and the related events and states

- station/src/Aevatar.Application.Contracts/Permissions/AevatarPermissionDefinitionProvider.cs
- station/src/Aevatar.Application.Contracts/Permissions/AevatarPermissions.cs
- station/src/Aevatar.Application.Contracts/Plugins/IPluginService.cs
- station/src/Aevatar.Application.Contracts/Projects/CreateProjectCorsOriginDto.cs
- station/src/Aevatar.Application.Contracts/Projects/CreateProjectDto.cs
- station/src/Aevatar.Application.Contracts/Projects/IProjectCorsOriginService.cs
- station/src/Aevatar.Application.Contracts/Projects/ProjectCorsOriginDto.cs
- station/src/Aevatar.Application.Contracts/Projects/UpdateProjectDto.cs
- station/src/Aevatar.Application/AevatarApplicationAutoMapperProfile.cs
- station/src/Aevatar.Application/Organizations/OrganizationService.cs
- station/src/Aevatar.Application/Plugins/PluginService.cs
- station/src/Aevatar.Application/Projects/ProjectCorsOriginService.cs
- station/src/Aevatar.Application/Projects/ProjectService.cs
- station/src/Aevatar.Application/Service/AgentService.cs
- station/src/Aevatar.CQRS/ElasticIndexingService.cs
- station/src/Aevatar.Domain/Projects/IProjectCorsOriginRepository.cs
- station/src/Aevatar.Domain/Projects/IProjectDomainRepository.cs
- station/src/Aevatar.Domain/Projects/ProjectCorsOrigin.cs
- station/src/Aevatar.Domain/Projects/ProjectDomain.cs
- station/src/Aevatar.HttpApi/Controllers/PluginController.cs
- station/src/Aevatar.HttpApi/Controllers/ProjectCorsOriginController.cs
- station/src/Aevatar.MongoDB/MongoDb/AevatarMongoDbContext.cs
- station/src/Aevatar.MongoDB/Projects/MongoDBProjectCorsOriginRepository.cs
- station/src/Aevatar.MongoDB/Projects/MongoDBProjectDomainRepository.cs
- station/test/Aevatar.Application.Tests/Origanzations/OrganizationServiceTests.cs
- station/test/Aevatar.Application.Tests/Projects/ProjectCorsOriginServiceTests.cs
- station/test/Aevatar.Application.Tests/Projects/ProjectServiceTests.cs
- station/test/Aevatar.MongoDB.Tests/MongoDb/Applications/Projects/MongoDBProjectCorsOriginServiceTests.cs
- Add cross-domain URL management
- Add plugin permissions
- Adjust the project domain logic
- Optimize the agent and ES api
> Feature: Developer platform v0.4

- station/ai/project_tracker.md
- station/src/Aevatar.Application/Projects/ProjectService.cs
- station/src/Aevatar.Application/Service/DeveloperService.cs
- station/src/Aevatar.HttpApi.Admin/Controllers/UserController.cs
- station/src/Aevatar.Kubernetes/Manager/KubernetesHostManager.cs
- station/test/Aevatar.Application.Tests/AevatarApplicationTestModule.cs
This PR implements comprehensive integration between project lifecycle management and developer services, enhancing automation and security across the platform.
Project Lifecycle Integration
> Project developer service integration

- Directory.Packages.props
- station/src/Aevatar.Application.Contracts/Account/IAccountService.cs
- station/src/Aevatar.Application.Contracts/Services/ILocalizationService.cs
- station/src/Aevatar.Application.Contracts/Services/LocalizationService.cs
- station/src/Aevatar.Application/Account/AccountService.cs
- station/src/Aevatar.Application/Constants/GodGPTExceptionMessageKeys.cs
- station/src/Aevatar.Application/Service/GodGPTService.cs
- station/src/Aevatar.Domain.Shared/GodGPTChatLanguage.cs
- station/src/Aevatar.GodGPT/Aevatar.GodGPT.csproj
- station/src/Aevatar.GodGPT/Dtos/AwakeningContentDto.cs
- station/src/Aevatar.GodGPT/Dtos/AwakeningStatus.cs
- station/src/Aevatar.GodGPT/Dtos/SessionTypeExtensions.cs
- station/src/Aevatar.HttpApi/Controllers/AccountController.cs
- station/src/Aevatar.HttpApi/Controllers/BlobStoringController.cs
- station/src/Aevatar.HttpApi/Controllers/GodGPTController.cs
- station/src/Aevatar.HttpApi/Controllers/GodGPTInvitationController.cs
- station/src/Aevatar.HttpApi/Controllers/GodGPTPaymentController.cs
- station/src/Aevatar.HttpApi/Controllers/GodGPTTwitterManagementController.cs
- station/src/Aevatar.HttpApi/Extensions/HttpContextExtensions.cs
- station/src/Aevatar.HttpApi/Handler/ChatMiddleware.cs
- station/test/Aevatar.Application.Tests/Account/AccountServiceTests.cs
1. Support multi-language
2. Add issue hints
3. Fix payment problem
4. Display subscription time
5. Awakening quotes & levels
> [GodGPT][1.23.0] Multi-lang, payments, etc

- station/src/Aevatar.Application/Service/AgentService.cs
- station/test/Aevatar.Application.Tests/Service/AgentServiceTests.cs
removes all sub-agents without deleting the agent; align tests to new semantics
> Fix: RemoveAllSubAgentAsync 

- framework/src/Aevatar.EventSourcing.MongoDB/MongoDbLogConsistentStorage.cs
- framework/test/Aevatar.EventSourcing.MongoDB.Tests/MongoDbLogConsistentStorageTests.cs
- Add cache to storage collection object whenever collection is create/retrieved from mongodb
- Add unit test to cover the changes
> [Enhancement] Storage Collection in Cache to Prevent Performance Degradation

- framework/src/Aevatar.Core/GAgentBase.cs
- framework/src/Aevatar.EventSourcing.Core/Storage/LogViewAdaptor.EventSourcing.cs
- framework/src/Aevatar.EventSourcing.MongoDB/MongoDbLogConsistentStorage.cs
- station/src/Aevatar.Application/Service/GodGPTService.cs
- station/src/Aevatar.HttpApi/Handler/ChatMiddleware.cs
Optimization of stress testing code
> Optimization of stress testing code

- Directory.Packages.props
- station/src/Aevatar.Application.Contracts/Account/SendRegisterCodeDto.cs
- station/src/Aevatar.Application.Contracts/Services/LocalizationService.cs
- station/src/Aevatar.Application/Account/AccountOptions.cs
- station/src/Aevatar.Application/Account/AccountService.cs
- station/src/Aevatar.Application/Account/AevatarAccountEmailer.cs
- station/src/Aevatar.Application/Constants/GodGPTExceptionMessageKeys.cs
- station/src/Aevatar.Application/Service/AppleSignatureVerificationService.cs
- station/src/Aevatar.Application/Service/DeviceMappingService.cs
- station/src/Aevatar.Developer.Host/AevatarDeveloperHostModule.cs
- station/src/Aevatar.GodGPT/Dtos/AppleAttributionReportDto.cs
- station/src/Aevatar.GodGPT/Dtos/DeviceMappingRegistrationDto.cs
- station/src/Aevatar.GodGPT/Dtos/SetUserProfileInput.cs
- station/src/Aevatar.HttpApi.Host/AevatarHttpApiHostModule.cs
- station/src/Aevatar.HttpApi/AevatarHttpApiModule.cs
- station/src/Aevatar.HttpApi/Controllers/AccountController.cs
- station/src/Aevatar.HttpApi/Controllers/AppleADNetworkController.cs
- station/src/Aevatar.HttpApi/Extensions/AppleAttributionServiceExtensions.cs
- station/src/Aevatar.HttpApi/Extensions/SecurityExtensions.cs
- station/src/Aevatar.HttpApi/Options/SecurityOptions.cs
- station/src/Aevatar.HttpApi/Services/ISecurityService.cs
- station/src/Aevatar.HttpApi/Services/SecurityService.cs
1. Email login password recovery
2. Add soul console messages to daily awakening quotes
3. SKAdNetwork proxy
4. Fix some bugs
> Feature/godgpt v1.26.0
